### ISSUE TITLE
Getting Issue in Babyswap Pools TVL calculation for tenfinance

### ISSUE THREAD

**Issue by sahilpant** [DefiLlama/DefiLlama-Adapters#1099]
The code runs smoothly up until babyPool's TVL is not counted . As soon as BabyPools are taken it gives below error.

(node:11000) UnhandledPromiseRejectionWarning: Error: missing revert data in call exception (code=CALL_EXCEPTION, version=providers/5.5.1)
    at Logger.makeError (C:\Users\SAHIL\Desktop\tenfi\defilama adapters\DefiLlama-Adapters\node_modules\@ethersproject\logger\lib\index.js:199:21)      
    at Logger.throwError (C:\Users\SAHIL\Desktop\tenfi\defilama adapters\DefiLlama-Adapters\node_modules\@ethersproject\logger\lib\index.js:208:20)     
    at C:\Users\SAHIL\Desktop\tenfi\defilama adapters\DefiLlama-Adapters\node_modules\@ethersproject\providers\lib\fallback-provider.js:652:52
    at Array.forEach (<anonymous>)
    at C:\Users\SAHIL\Desktop\tenfi\defilama adapters\DefiLlama-Adapters\node_modules\@ethersproject\providers\lib\fallback-provider.js:632:61
    at step (C:\Users\SAHIL\Desktop\tenfi\defilama adapters\DefiLlama-Adapters\node_modules\@ethersproject\providers\lib\fallback-provider.js:48:23)    
    at Object.next (C:\Users\SAHIL\Desktop\tenfi\defilama adapters\DefiLlama-Adapters\node_modules\@ethersproject\providers\lib\fallback-provider.js:29:53)
    at step (C:\Users\SAHIL\Desktop\tenfi\defilama adapters\DefiLlama-Adapters\node_modules\@ethersproject\providers\lib\fallback-provider.js:33:139)   
    at Object.next (C:\Users\SAHIL\Desktop\tenfi\defilama adapters\DefiLlama-Adapters\node_modules\@ethersproject\providers\lib\fallback-provider.js:29:53)
    at fulfilled (C:\Users\SAHIL\Desktop\tenfi\defilama adapters\DefiLlama-Adapters\node_modules\@ethersproject\providers\lib\fallback-provider.js:20:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sahilpant** [comment]
Ten.finance TVL is zero where as I ran the test script on ten.finance it gives TVL

**Comment by waynebruce0x** [comment]
This seems resolved, now printing 87M - can this issue be closed?
