### ISSUE TITLE
Testing new adapters fails with timeout query for buildPricesGetQueries

### ISSUE THREAD

**Issue by rvaitkus23** [DefiLlama/DefiLlama-Adapters#11131]
Hello,

A couple of days ago I could successfully test my new adapter. Today it fails with 
```
PromisePoolError: connect ETIMEDOUT 2606:4700:10::6816:3646:443
Truncated error stack:
    at PromisePoolError.createFrom (/Users/ric/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
    at async Promise.all (index 0)
```
While debugging, I found that time-out happens at this line
```
tokenData.push((await axios.get(query)).data.coins)
```
The query URL is `https://coins.llama.fi/prices/current/coingecko:usd-coin,coingecko:weth`
Executing query browser it does not fail and does not time out. Wrapping this line in try-catch block I get this error
```
AxiosError: connect ETIMEDOUT 2606:4700:10::6816:3646:443
    at AxiosError.from (/Users/ric/DefiLlama-Adapters/node_modules/axios/dist/node/axios.cjs:841:14)
    at RedirectableRequest.handleRequestError (/Users/ric/DefiLlama-Adapters/node_modules/axios/dist/node/axios.cjs:3106:25)
    at RedirectableRequest.emit (node:events:517:28)
    at eventHandlers.<computed> (/Users/ric/DefiLlama-Adapters/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/Users/ric/DefiLlama-Adapters/node_modules/axios/dist/node/axios.cjs:4224:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PromisePoolExecutor.handler (/Users/ric/DefiLlama-Adapters/test.js:368:21)
    at async Promise.all (index 0)
    at async PromisePoolExecutor.drainActiveTasks (/Users/ric/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:537:9)
    at async PromisePoolExecutor.drained (/Users/ric/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:527:9)
    at async PromisePoolExecutor.process (/Users/ric/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:335:16)
    at async PromisePoolExecutor.start (/Users/ric/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:272:16)
    at async computeTVL (/Users/ric/DefiLlama-Adapters/test.js:365:22)
    at async getTvl (/Users/ric/DefiLlama-Adapters/test.js:56:24) {
  port: 443,
  address: '2606:4700:10::6816:3646',
  syscall: 'connect',
  code: 'ETIMEDOUT',
  errno: -60,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'axios/1.7.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://coins.llama.fi/prices/current/coingecko:usd-coin,coingecko:weth',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/prices/current/coingecko:usd-coin,coingecko:weth',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'coins.llama.fi',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/prices/current/coingecko:usd-coin,coingecko:weth'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /prices/current/coingecko:usd-coin,coingecko:weth HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.7.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: coins.llama.fi\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/prices/current/coingecko:usd-coin,coingecko:weth',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'coins.llama.fi',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://coins.llama.fi/prices/current/coingecko:usd-coin,coingecko:weth',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ETIMEDOUT 2606:4700:10::6816:3646:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -60,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '2606:4700:10::6816:3646',
    port: 443
  }
}
```
Why this could happen?

**Comment by rvaitkus23** [comment]
Looks like it is working again.
Apologies for disturbance
